### ISSUE TITLE
Templates from a local image are listed in "downloaded". "local" would be a better name

### ISSUE THREAD

**Issue by philippeback** [pharo-project/pharo-launcher#101]
![image](https://user-images.githubusercontent.com/2128441/39677767-dfaded46-5180-11e8-8202-6f3f75d6f0bf.png)

**Comment by VincentBlondeau** [comment]
Indeed, since you can also create your own templates:

Name: PharoLauncher-Core-VincentBlondeau.187
Author: VincentBlondeau
Time: 24 May 2018, 11:00:34.736507 am
UUID: 7b713d2a-5929-0d00-94d3-2609047b713a
Ancestors: PharoLauncher-Core-ChristopheDemarey.186

Change template name
https://github.com/pharo-project/pharo-launcher/issues/101

**Comment by demarey** [comment]
This fix is not good. The templates group name was `local templates` at the beginning. I changed it to `Downloaded templates`which is also not good because you can define local templates.
We should change it to `Downloaded or local templates`

**Comment by philippeback** [comment]
Read above.

downloaded doesn't work because I can set one of my local images as a  template and downloaded then doesn't make any sense, is confusing, ...

If you do not like "local templates" (which is actually what they are), just say "templates" (but I'd love to know they are local) and "My Templates" is out of fashion. Microsoft moved away from that option (yay).

**Comment by demarey** [comment]
> downloaded doesn't work because I can set one of my local images as a template and downloaded then doesn't make any sense, is confusing, ...

That's why I proposed `Downloaded **or** local templates`. 
In any case it is confusing because this entry mixes a template cache (downloaded templates from files.pharo.org or a jenkins server) with a local user template repository.
We plan to fix that by doing another version of the UI

> If you do not like "local templates" (which is actually what they are), just say "templates" (but I'd love to know they are local) and "My Templates" is out of fashion. Microsoft moved away from that option (yay).

It is not that I do not like _local templates_ but it is also confusing. Stef asked to change this name because it was confusing for him. I think whatever we will pout will be confusing because of the UI design that is confusing. Before we get this new UI, why not using _templates_. It is ok for me.

**Comment by philippeback** [comment]
With a tooltip saying "Local or Downloaded Templates"

**Comment by philippeback** [comment]
I agree that the two should be segregated.
