### ISSUE TITLE
Template Cleared at Startup setting is enabled, making it weird when trying to use the template feature

### ISSUE THREAD

**Issue by philippeback** [pharo-project/pharo-launcher#102]
It would be better to have it unchecked by default.

![image](https://user-images.githubusercontent.com/2128441/39677779-122b7c70-5181-11e8-944e-5de2c169858c.png)

**Comment by VincentBlondeau** [comment]
Seems fair!

Name: PharoLauncher-Spec-VincentBlondeau.68
Author: VincentBlondeau
Time: 24 May 2018, 11:21:25.481507 am
UUID: 3b48ca74-5929-0d00-94d4-3a84047b713a
Ancestors: PharoLauncher-Spec-ChristopheDemarey.67

change default of template cleared at startup to false instead of true
https://github.com/pharo-project/pharo-launcher/issues/102
