### ISSUE TITLE
localDirectory stored in system-settings.ston -> newly created images accessing the wrong localDirectory path

### ISSUE THREAD

**Issue by sasiflo** [pharo-project/pharo-launcher#120]
When storing the settings in Settings Browser, an entry for System->Local Directory is stored in a configuration directory / file used by all images (file system-settings.ston in ~/.config/pharo/7.0 on Linux). Some other paths as pharo-local" are calculated based on this entry. Running just one image at  the time, there is no problem. The entry is updated to a path for the running image. But running two images in parallel the second one throws some errors and reads the wrong setting for localDirectory.

The notifications are vanishing to fast. It is something about "cannot update ...". I assume it could not write to the system-settings.ston file.

My environment is Debian (buster/sid) Linux 64 Bit and recent Pharo 7.0 / 64 Bit (checked build 1050 -> 1053)

![grafik](https://user-images.githubusercontent.com/1850927/41368823-55556134-6f43-11e8-847a-2195d59fa360.png)
![grafik](https://user-images.githubusercontent.com/1850927/41368848-72cf2c86-6f43-11e8-8165-c78fd41b3b32.png)

**Comment by sasiflo** [comment]
Perhaps it is a general issue for Pharo and not caused by PharoLauncher.

**Comment by demarey** [comment]
Thanks for the report.
Indeed, this problem is a general pharo isssue. PharoLauncher stores its own settings in a dedicated file. To me, having a global setting for a `pharo-local` directory is wrong because it is supposed to be local to the image. People will have a lot of issues if they share the same pharo-local directory.

Could you pleas open a bug entry on https://pharo.fogbugz.com/f/ ?

**Comment by sasiflo** [comment]
I open an issue on fogbugz/manuscript.

**Comment by sasiflo** [comment]
https://pharo.fogbugz.com/f/cases/22141/UserLocalDirectory-pharo-local-in-system-settings-ston-problem-when-running-multiple-images
