### ISSUE TITLE
Move development to Pharo 7

### ISSUE THREAD

**Issue by guillep** [pharo-project/pharo-launcher#151]

**Comment by guillep** [comment]
I've found no dependencies on Versionner finally. Doing only some migration of #asIcon.

**Comment by demarey** [comment]
Why do you want to move PharoLauncher to Pharo 7? Pharo 7 is still in development and it looks strange to me to rely on an ongoing-work.

**Comment by guillep** [comment]
It should at least be loadable, work and we should be able to develop on pharo 7. There are lots of enhancements in Pharo7 that are really important and make it much easier to contribute: from the management to the working directory to fixes in streams, and not mentioning iceberg.

This does not mean that the launcher should packaged with pharo 7, but that we shoud be able to develop with it.

**Comment by demarey** [comment]
If we can manage to have PharoLauncher in current stable and current alpha, of course it's fine. I was not sure because of API changes, etc. And what if we start to use features only in current alpha? @pavel-krivanek I do not agree with you. PharoLauncher and Pharo are 2 different products. We do not have to couple releases of Pharo and PharoLauncher. In my mind, PharoLauncher should always use the latest Pharo stable for each new release but it does not mean we have to create a new release because a new version of Pharo is out.

**Comment by pavel-krivanek** [comment]
It is a PR must. It would not look good if you tell people: look, here is the new stable version. But not good enough to be used for such basic task like running of itself. Moreover. In future releases, the new release may require different VM version than the old stable one. 
And this way we push the team members to use Pharo 7 and report/solve bugs

**Comment by demarey** [comment]
>   It would not look good if you tell people: look, here is the new stable version. But not good enough to be used for such basic task like running of itself.

Why do you say that? You would be true if you do a new release of Pharo Launcher without using the new stable. But I do not see what would not look good to do not provide a new launcher release without any new functionality. As a Pharo Launcher user, I do not care to get a new version without improvements. PharoLauncher does not have to follow the release process of Pharo.

> In future releases, the new release may require different VM version than the old stable one.

This problem is not related to the discussion. Pharo Launcher should be able to download the right VM whatever version it is running on.

> And this way we push the team members to use Pharo 7 and report/solve bugs

Here I disagree. Team members can/should develop on Pharo 7 but you cannot make Pharo Launcher a way to discover bugs. Do not forget it is used by newcomers.

**Comment by pavel-krivanek** [comment]
one more point - we want to have the Launcher as a standalone application with no development tools etc. This is not possible in Pharo 6. Anyway, we are talking about the development version of Pharo Launcher.

**Comment by demarey** [comment]
I agree there a lot of things we want for PharoLauncher in Pharo 7 (read only app, bootstrap, etc). For all these reasons, I would not see badly to use Pharo 7 (even for a release) before it becomes stable, but only because it comes with needed features for the Launcher. The discussion above was more general.

**Comment by pavel-krivanek** [comment]
Well, there is, at least, dependency on MCModel2MTModelVisitor in PhLAboutCommand>>#launcherMTProject

**Comment by demarey** [comment]
yes, it used to determine the PL version for the about box.
Once we switch to Cargo to manage PL, it will be useless

**Comment by guillep** [comment]
we can just use a `git describe`, no?

**Comment by demarey** [comment]
would be better to ask Iceberg, no?

**Comment by guillep** [comment]
Maybe, but the launcher is not loaded through iceberg yet. And the support in Pharo6 is not the same as in Pharo7...
