### ISSUE TITLE
Jenkins does not check the PR anymore

### ISSUE THREAD

**Issue by VincentBlondeau** [pharo-project/pharo-launcher#256]
https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/PharoLauncher/pr

![image](https://user-images.githubusercontent.com/4706329/45975792-e97f5c00-bff9-11e8-881e-36a7963ed87e.png)

**Comment by guillep** [comment]
@demarey was playing yesterday with the permissions and the CI...

**Comment by guillep** [comment]
Ok, the PR settings was set to only build PRs coming from people with write permissions. I've opened it to everyone.

I think this is a *must to*... @demarey?
Bah, otherwise we need to have a setting with two CIs, one for owners on jenkins, one for contributors on travis (which must run the tests at least). But this would mean that we are not testing the construction of the build artifacts, packaging, installers and so on...

What do you think?

**Comment by demarey** [comment]
I think it was done like that because the build process is signing the application. We cannot sign something that was not approved. We should work on that problem to enable PR builds, by example we could just avoid signing when building a PR

**Comment by guillep** [comment]
But we can write the CI so that it signs only things that are not PRs.

**Comment by demarey** [comment]
yes, it is what I wrote :)

**Comment by demarey** [comment]
fixed in 2c52d435a6194e7f932be86a786907ac2514c229
