### ISSUE TITLE
Rename the "local" template group to "downloaded templates"

### ISSUE THREAD

**Issue by DamienCassou** [pharo-project/pharo-launcher#26]

**Comment by bpieber** [comment]
I like this suggestion. I was confused about what local meant and how it got populated.

**Comment by demarey** [comment]
I agree.
Now fixed in Launcher repo.
-----------
Name: PharoLauncher-Core-ChristopheDemarey.147
Author: ChristopheDemarey
Time: 5 December 2017, 9:47:19.335159 pm
UUID: f6bf89ad-ff1b-0d00-9e28-ecca07813032
Ancestors: PharoLauncher-Core-TorstenBergmann.146, PharoLauncher-Core-ChristopheDemarey.142, PharoLauncher-Core-ChristopheDemarey.144

Rename PhLLocalTemplateGroup to PhLDownloadedTemplateGroup. Fixes issue #26.

Merge with previous versions
