### ISSUE TITLE
Add a Location column for Current Images list 

### ISSUE THREAD

**Issue by stephensmith9** [pharo-project/pharo-launcher#298]
For me the most important detail about the list of current images is the location of the image on my system. Having to click to view image details is too time consuming when I have many images in the list. I would argue that this is even more important than the Template column and should be placed before it (better still, it would be nice to be able to drag and drop the order of the columns). 

![pharo-launcher-enhancement](https://user-images.githubusercontent.com/7142084/51804859-9c272b80-2233-11e9-9db0-d6ad96cd91a3.png)

**Comment by demarey** [comment]
Hi,
I'm not sure to well understand your request. Images are all located into the same folder with Pharo Launcher. Do you want to see the same information for each row?

**Comment by stephensmith9** [comment]
I think my understanding of the launcher's configuration settings might have been a bit different than what I now understand it to be. 

I tend to use my filesystem to organize my images. So I may have several images in different locations on my system, for example:

D:\pharo\images\test\test1.image
D:\pharo\images\prod\prod1.image
D:\pharo\images\research\research-project1.image
...and other locations, even on different drives as well.

And my PharoLauncher program is installed somewhere entirely different, as I keep my programs (including the PharoLauncher program in this case) separate from my data typically. 

The option was there to specify a different folder for images and vms, so I took advantage of that (though I didn't realize that I was locked in to one images folder - but as there is only one option to specify an images folder I see that now). To me, this is one of the biggest advantages of Pharo Launcher - to consolidate all my images in one place to launch. Maybe this is not the intended use case for Pharo Launcher? 

I see now that the design calls for all images to be in one place (under their respective subfolders of course). To me this is restrictive. Why should I have to install all of my images to the same folder/drive? That is just my personal preference, but I'm sure there are others who organize images in different folders and drives on their system?

Anyway, still a great program, so thanks for making it available, and I will now reorganize my images to one place to accommodate the structure that PharoLauncher expects. However, if there is a wish list of features, this would be my first wish - for the ability to browse to an existing image anywhere on my filesystem and have it appear in the list of available images to launch. Then my request to show the location of the image on the filesystem will make more sense.

Hope that helps explain my request.
Stephen.

**Comment by demarey** [comment]
I now understand your request. :)
I agree that it would be nice to ba able to put images wherever you want. From a technical point of view, having image spread everywhere on the disk means than PharoLauncher needs some metadata to know the list of images (and their location) it manages. A drawback of this feature is that it would be hard to keep in sync Pharo Launcher metadata on images: what happens if you move an image on the filesystem? what happens if you remove an image from the file system?
If one accept that PL metadata on images could be desynchronized from the data on the filesystem, then it is ok. 
If such a feature is still interesting for you, I would suggest to open a new issue (feature request) for it. It could be clearer than keeping this issue. Then, I would close this one. I cannot tell you if the feature will be implemented and when. I think it should be discussed with other users to see if it is something important useful / important for them.

For now, PL cannot list images that are not in the image folder but it can :
- run them from any place,
- import them to the default location.
You can do that with the import button (just before the remove button).

**Comment by stephensmith9** [comment]
Agreed, this would be a large change to the system. I will close this issue and consider a feature request but after some more thought on my end. Thanks for the responses and feedback!
