### ISSUE TITLE
HTTP Proxy authentication missing from settings again

### ISSUE THREAD

**Issue by chaerle** [pharo-project/pharo-launcher#358]
1) The proxy authentification settings are not present in the settings. See isuue #30 

2) I still gives proxy authentication error 407, if I try to set these manualla with:
NetworkSystemSettings proxyUser: 'myuser'; proxyPassword: 'mypassword'.

Platform Windows 7, active directory domain network.

**Comment by demarey** [comment]
Thanks for the report.
Could you test with http://files.pharo.org/pharo-launcher/bleedingEdge/ to see if the fix is ok?

<blockquote><img src="/_h5ai/client/images/app-16x16.ico" width="48" align="right"><div><strong><a href="http://files.pharo.org/pharo-launcher/bleedingEdge/">index · styled with h5ai 0.22.1 (http://larsjung.de/h5ai/)</a></strong></div><div>index styled with h5ai 0.22.1 (http://larsjung.de/h5ai/)</div></blockquote>

**Comment by evenremy** [comment]
The proxy authentification settings are not present in the settings of the Launcher.

**Comment by demarey** [comment]
Hi @evenremy 
Are you sure?
I can see them. See the screenshot
![Capture d’écran 2022-04-14 à 15 50 57](https://user-images.githubusercontent.com/2494203/163405213-a41e9492-eda6-47df-8db2-9c9bec0069ea.png)

**Comment by evenremy** [comment]
Hi,
I am looking for the authentication settings (user name and password) accessible in all pharo images but not in the launcher. With the launcher every download will fail behind our proxy. I am able to access these settings with the developer mode but it's not saved (not convenient and I didn't try on this new version)...
![proxy auth](https://user-images.githubusercontent.com/33895/163421500-62783413-7d40-43f3-9094-b062ddcc6864.PNG)

**Comment by demarey** [comment]
Oh, yes right.
This was lost during a merge.
I will put it back. Thanks.
