### ISSUE TITLE
Handle multiple user accounts on OSX - get #primitiveFailed on ensureDirectory

### ISSUE THREAD

**Issue by macta** [pharo-project/pharo-launcher#363]
On OSX, I have 2 user accounts (one for the office, one for personal) - and I want to run PharoLauncher in both accounts.

Currently - they seem to share a location setting, and so I get an primitiveFailed error when I launch in my other accoutn as it tries to ensureDirectory on a directory from the other account instead of having its own settings for this seperate user. (its LauncherCoreDir that is showing the wrong directory for the other user - see photo)

![image](https://user-images.githubusercontent.com/5553623/66470930-6f920780-ea82-11e9-9893-1b3ec7493049.png)

**Comment by demarey** [comment]
Hi,
Sorry for the late answer. I'm doing a pass on bugs to prepare the next Pharo Launcher version.
The bug is strange. I checked the code and you shouldn't get the same directory.
For each of your users, could you open Pharo Launcher, then open the playground (cmd + o + w), then print the result of:
```smalltalk
PlatformResolver forCurrentPlatform launcherUserFilesLocation fullName
```
It is the code used by PL. It should resolve to home dir / Documents / Pharo.

My guess is that there was a save of the image with the value of launcherCoreDir cached.

**Comment by macta** [comment]
That’s the point though - if you have a single instance of the launcher in /Applications - the second user will launch it ( as apps are shared) and they will get the wrong directory - that if the first user to use launcher. It shouldn’t save this value in the image, but in a per user setting?

It’s a bit obscure I guess, I got over it by having 2 launcher apps , but it should really save see tings somewhere else I’d we have a generic way to do that.

**Comment by demarey** [comment]
Using FileLocator will solve the problem when not customizing pathes.
I will take a more "radical" approach by just not saving changes to the image when exiting Pharo Launcher. Settings still can be stored with the store button in the user preferences directory

**Comment by demarey** [comment]
should be solved in the latest dev version
