### ISSUE TITLE
Pharo Launcher settings are not being persisted

### ISSUE THREAD

**Issue by chicoary** [pharo-project/pharo-launcher#463]
### Setting up the theme.

![setting theme](https://user-images.githubusercontent.com/7659991/80097907-6bbb6380-8542-11ea-975a-b9fb6c114dc3.png)

### Theme successfully configured to Pharo Dark.

![after setting theme](https://user-images.githubusercontent.com/7659991/80097951-7b3aac80-8542-11ea-993d-4b5eea9a589d.png)

### After relaunching the theme does not persist.

![after relaunching](https://user-images.githubusercontent.com/7659991/80097964-7fff6080-8542-11ea-8046-53a4701901a7.png)

**Comment by demarey** [comment]
Hi,

Thanks for the report.
Did you click on the "store settings" button in the toolbar?
Pharo Launcher image is not saved, so if settings are not stored, they will only be valid for the current session.

**Comment by chicoary** [comment]
Hi,
I did what you recommended. 

It works. 

But if I remember correctly in previous versions, you didn't have to save the configuration. Or I'm confusing with the Pharo IDE where the image saving made me expect the same from the Pharo Launcher. 

Thanks. 

I'll close the issue myself.

**Comment by demarey** [comment]
Hi,

You remember correctly. In the previous image, it was possible to save Pharo Launcher image. In fact, it was done each time you click on the "Quit" button.
It is now disabled because some users got problems with saved paths in the Pharo Launcher app, shared with multiple users on the same machine. See #463 for more details.
Also, I think it is a good move to have the app 'unchanged'. It could allow (with some more work) to install the app where you do not have write permissions.

Regards
