### ISSUE TITLE
Launcher quits when attempting to load Pharo Dawn Theme

### ISSUE THREAD

**Issue by eMaringolo** [pharo-project/pharo-launcher#464]
**Describe the bug**
The launcher quits silently when attempting to load the [PharoDawnTheme](https://github.com/sebastianconcept/PharoDawnTheme)

**To Reproduce**
1. Open Pharo Launcher
2. Go to Settings
3. Enable Development Environment
4. Evaluate: 
```smalltalk
Metacello new 
	baseline: 'PharoDawnTheme';
	repository: 'github://sebastianconcept/PharoDawnTheme';
	load.
```

**Expected behavior**
To load the theme.

**Version information:**
 - OS: Windows 10
 - Version: [e.g. 1.6.1]

**Comment by demarey** [comment]
It took me a while to determine the source of the problem but I got it.
The image crashes because it tries to use libgit that is not initialized in a default Pharo image.
Doing `LGitLibrary uniqueInstance initializeLibGit2` before the loading should solve the problem.
I will add this action when going in development mode.

**Comment by eMaringolo** [comment]
Thank you!
