### ISSUE TITLE
fix Moose images download

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-launcher#535]
**Describe the bug**
A change in GitHub releases url breaks Moose images download

See https://github.com/svenvc/zinc/issues/69

Fix:
```Smalltalk
PhLDownloadManager>>#newHTTPClientForUrl: url
	^ ZnClient new
		signalProgress: true;
		url: url;
		enforceHttpSuccess: true;
		withOptions: [ :options | options at: #queryKeyValueSafeSet put: (ZnOptions queryKeyValueSafeSet \ '/;') ];
		ifFail: [ :exception | self downloadFailureForUrl: url ];
		yourself
```
It is need to load a new version of Zinc:
```Smalltalk
Metacello new
  repository: 'github://svenvc/zinc/repository';
  baseline: 'ZincHTTPComponents';
  load.
````

**Comment by fuhrmanator** [comment]
I am using the latest PL 3.0 in Windows 10 and still hitting this problem. Is there maybe a zinc configuration issue?

> Pharo Launcher version: 3.0

![Pharo_8ZuIbPRZFu](https://user-images.githubusercontent.com/7606540/163441996-53ac73b6-dbac-4ab1-8aa5-049c29aa0617.gif)

I'd like to help write a test for this so the regression doesn't happen.

**Comment by fuhrmanator** [comment]
Finally, I think it's a problem with the Moose releases on GitHub and the "Official releases" (the original one `Moose9-development.zip` doesn't actually exist anymore). I will create another issue (probably for Moose?). Somehow it would be nice to get a "Not found" error rather than a generic `PhLDownloadError` - the original Zinc issue was also the same manifestation, if I"m not mistaken.

**Comment by demarey** [comment]
Hi Christopher,

Thank you for the notification.
I updated the official sources to fix Moose urls and I also took some minutes to have a better display of http errors. The http error code and reason will now be displayed as well as the url.
