### ISSUE TITLE
"Basic launch" does not do its job in Pharo 10

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#540]
**Describe the bug**
I tried to launch a Pharo 10 image without loading my settings by launching the image with "Basic launch" but my setting still got loaded in the image. 

I checked and this does not happen with Pharo 9. 

**Version information:**
 - OS: Windows 11
 - Launcher Version: 2.4

**Comment by demarey** [comment]
`PhLLaunchConfiguration` has a check in `useSettings:` that prevents the `--no-default-preferences` option to be added on Pharo versions < 30 (option not supported.
```smalltalk
useSettings: aBoolean
	"Cannot skip Pharo settings before Pharo 3.0"
	self image ensurePharoVersion < '30' ifTrue: [ ^ self ].

	usePharoSettings := aBoolean.
```
As you can see, this check, based on string comparison will fail for Pharo 10: '100' < '30' is true.
The fix is to use integer comparison.
