### ISSUE TITLE
Error downloading Pharo 10 for Windows (64bit) from Launcher

### ISSUE THREAD

**Issue by stephensmith9** [pharo-project/pharo-launcher#556]
When downloading the Pharo 10.0 - 64bit (stable) image, the process fails with a dialog box saying "Error downloading 'https://files.pharo.org/get-files/100/pharo64-win-stable.zip'.

Looking at the files.pharo.org site, the actual filename for Pharo 10 for Windows is pharo64-windows-stable.zip. How do we tell the Launcher to use the correct filename? (to use 'windows' instead of 'win')

**Comment by stephensmith9** [comment]
Using Launcher version 2.2. Sorry, forgot to mention that.

**Comment by demarey** [comment]
Hi Stephen,

Indeed, Pharo Launcher 2.2 cannot handle Pharo 9 + images. Is it only managed since v2.3 : https://github.com/pharo-project/pharo-launcher/releases/tag/2.3
You need to download the latest Pharo Launcher (3.0.1) from https://pharo.org/download.

<blockquote><img src="https://opengraph.githubassets.com/ae0bc15902ca8a6b1a352d2637feea6b06558d36c4a50bf0fbb89408300080c9/pharo-project/pharo-launcher/releases/tag/2.3" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/pharo-project/pharo-launcher/releases/tag/2.3">Release Pharo Launcher 2.3 · pharo-project/pharo-launcher</a></strong></div><div>Pharo Launcher 2.3
Changelog
New features:

Apple M1 SoC detection to run arm64 Pharo VM when applicable
Updated VM urls for Pharo 9 and above
Squeak and GToolKit support (contributed by Sean DeNig...</div></blockquote>
<blockquote><img src="/files/favicon.ico" width="48" align="right"><div><strong><a href="https://pharo.org/download">Pharo - Download</a></strong></div></blockquote>
