### ISSUE TITLE
Working directory should be inherited from CLI

### ISSUE THREAD

**Issue by cdlm** [pharo-project/pharo-launcher#559]
**Context:** launching an image via CLI, using the `pharo-launcher image launch IMAGENAME` command

**What happens:** the working directory is the image directory (`FileSystem disk workingDirectory = FileLocator imageDirectory asFileReference` is true).

This is a problem because the user context is lost.

**What _should_ happen:** the working directory (value of `$PWD` in the shell that invokes the `pharo-launcher` wrapper script) should be inherited by the image.

**Comment by cdlm** [comment]
See `PhLLaunchImageProcessConfigurator >> visit`:
```smalltalk
visit
	process := PhLProcessWrapper new.
	process workingDirectory: self imageFile parent pathString.
	…
```

(a quick test after changing that seems to work, PR incoming)

**Comment by Bajger** [comment]
@cdlm Hi Damien! It's been a while since you did this change, but could you look at it? CI is failing after integration, see: https://ci.inria.fr/pharo-ci-jenkins2/job/PharoLauncher-Pipeline/job/feature%252Fcmd-line/18/console
I think this is because workingDirectory on image launch configuration returns nil. Probably existing images have already referring to launch config objects:
```
PhLImage>>defaultLaunchConfiguration
	^ launchConfigurations 
		detect: [ :each | each name = PhLLaunchConfiguration defaultName ]
		ifNone: [ PhLLaunchConfiguration defaultWithImage: self ]
```
probably existing image launch configuration instances need to be re-initialized with correct working directory. What do you think? 


<blockquote><img src="/pharo-ci-jenkins2/static/5e712aea/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/job/PharoLauncher-Pipeline/job/feature%252Fcmd-line/18/console">PharoLauncher-Pipeline » feature/cmd-line #18 Console [Jenkins]</a></strong></div></blockquote>

**Comment by Bajger** [comment]
Waiting to CI to be up again. It should be fixed. by PR #604

**Comment by Bajger** [comment]
Resolved by linked PRs.
