### ISSUE TITLE
Linux zip structure needs to be review

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-launcher#58]
Today I installed Fedora 27 on my machine and I wanted to install PharoLauncher.

I downloaded the zip for version 1.0.1 but I had some struggle to launch it. When launching the "pharo" script I got error because it did not found the vm. 

I found that the vm was in a "tmp" folder and I needed to execute rename this folder to "vm" in order for the launcher to work.

**Comment by demarey** [comment]
Hi Cyril,

This problem comes fro an update I did on some pharo build scripts used both by the launcher and pharo itself. Pharo vm packaging was broken after that. It is now reverted.
Everything should be ok now.
Last launcher development version is now available here: http://files.pharo.org/pharo-launcher/bleedingEdge/
