### ISSUE TITLE
Does not launch images on Windows

### ISSUE THREAD

**Issue by webwarrior-ws** [pharo-project/pharo-launcher#68]
Version 1.1; installer from `files.pharo.org`.
If _launch on exit_ is enabled, launcher exits, otherwise does nothing.
Tried on 2 different machines: one with Windows 7 x64, another one with Windows 10 x64.

**Comment by demarey** [comment]
Hi,

Thanks for the report. Maybe the error is related to #67.
If so, you can uncheck the 'launch a login shell' in settings and images should be launched.
If you prefer, there is already a build with the fix for #67: http://files.pharo.org/pharo-launcher/bleedingEdge/pharo-launcher-installer-bleedingEdge-2018.01.19-x86.exe

**Comment by webwarrior-ws** [comment]
> If so, you can uncheck the 'launch a login shell' in settings and images should be launched.
It worked, thanks

**Comment by demarey** [comment]
ok, then I will publish a new bugfix version ASAP

**Comment by VincentBlondeau** [comment]
Integrated in latest stable image version
